github:
 user: sisipka
 token: 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
 secret: ulokchmxxlhmwbelbuawkjrtrpljnqjkozilbbuvnkmmkiimkhelimgvraqtqrvdzjhmckbpxenplyqfccqskhgldntohcsnncgsdjvflwlszhfbyjsascvaepaajzgh
# Replace this with your own repo whitelist:
orgWhitelist: "github.com/sisipka/*" # Don't forget the "*" to whitelist all the repository of your group

service:
 type: LoadBalancer
 port: 80

# AWS credentials outputted when created your Kubernetes cluster on EKS
aws:
  credentials: |
    [default]
    aws_access_key_id=YCAJEejVa1KaHadoWcrKrxQ5x
    aws_secret_access_key=YCMN_ZAZTMs1cqnN1vNjFrBI8vfWwpCbr_wCg5x6

repoConfig: |
 ---
  repos:
  - id: /.*/
    branch: /.*/
    workflow: myworkflow
    apply_requirements: [approved, mergeable]
    allowed_overrides: [apply_requirements, workflow, delete_source_branch_on_merge]
    allowed_workflows: [myworkflow]
    allow_custom_workflows: true
  workflows:
    myworkflow:
      plan:
        steps:
        - run: echo "In Terraform Init and Plan"
        - init
        - plan:
            extra_args: ["-lock=", "false"]
      apply:
        steps:
        - run: echo "In Terraform Apply"
        - apply

podTemplate:
  annotations: {}
  labels: {}

statefulSet:
  annotations: {}
  labels: {}
  securityContext:
    fsGroup: 1000
    runAsUser: 100

ingress:
  enabled: false


resources:
  requests:
    memory: 0.5Gi
    cpu: 100m
  limits:
    memory: 0.5Gi
    cpu: 100m

# Disk space for Atlantis to check out repositories
dataStorage: 0.5Gi

replicaCount: 1
